version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data/chunks:/tmp/loki/chunks
      - ./loki-data/index:/tmp/loki/index
      - ./loki-data/cache:/tmp/loki/boltdb-cache
      - ./loki-data/compactor:/tmp/loki/compactor
      - ./loki-data/wal:/tmp/loki/wal

  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - ./logs:/app/logs            # Spring 로그 파일이 여기에 있어야 함
    command: -config.file=/etc/promtail/config.yaml

  grafana:
    image: grafana/grafana:10.4.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
