server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: info-logs
    static_configs:
      - targets: [dummy]
        labels:
          job: spring
          level: info
          __path__: /app/logs/info/*.log

  - job_name: error-logs
    static_configs:
      - targets: [dummy]
        labels:
          job: spring
          level: error
          __path__: /app/logs/error/*.log
