server:
  port: 8080

spring:
  application:
    name: news-gpt-back
  config:
    import: optional:dotenv:.env
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/news_gpt
    username: ENC(lBPAGZTtXv7Eov0O6BMY9w==)
    password: ENC(lBPAGZTtXv7Eov0O6BMY9w==)
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

openai:
  max-tokens: 400
  temperature: 0.3
  prompt-version: 1